src/Widgets/Player/TimeWidget.vala

Sometimes when you click on seekbar to change playback time, gtk scale jumps back to where it's currently playing. That usually happens when you click quickly. Longer press usually works ok..

Fixed jumping seekbar

---

src/Audience.vala
src/Objects/Video.vala
src/Services/Inhibitor.vala
src/Services/LibraryManager.vala
src/ZeitgeistManager.vala

We should not call `error` since it terminates the program, we call `warning` instead. Fixes #25 and #36.

Do not terminate the program when some method fails

---

src/Window.vala

This fixes #30.
If you clicked play/pause button with mouse and then pressed space bar, it acted as if you pressed it twice.
It was similar with playlist and settings buttons - space activated them if you focused them before with mouse.

Don't allow space key to process further

---

src/Widgets/Player/PlayerPage.vala

navigating video with arrow keys back before 00:00 opened welcome screen

Disallow setting playback before start

---

src/Audience.vala

It was used for the about dialog, however that was removed by #34

Remove deprecated app_icon field

---

src/Window.vala

Restores functionality of making the video player fullscreen when maximizing the window
~Blocked, depends on https://github.com/elementary/gala/pull/58 or the window will break~
The bug is now fixed in Juno, so once Videos is done supporting Loki this can be merged

Make video fullscreen on maximize

---

data/CMakeLists.txt

Installing to `appdata` is deprecated. This should go to `metainfo` now

Install appdata.xml to metainfo

---

src/Widgets/NavigationButton.vala

1. open Videos
2. click Browse Library
... there's tiny navigation button with no text at first
No idea why gtk doesn't show label at first even though it is set. Just initializing label property apparently fixes the issue.

Fix 'Back' button label not shown at first

---

src/Widgets/Player/SettingsPopover.vala

fixed cycling over subtitle and audio lists with 'A' and 'S' keys:
* it worked properly only after you opened settings popover
* you could cycle to empty item in subtitles or over 2 audio items when combobox is disabled
- subtitle changed property did not notify before
Looks like this also fixes #35

Settings popover bugfixes

---

src/Widgets/Player/PreviewPopover.vala

Popover width was always 200px. That would make popover too big for vertical videos.
This PR calculates popover size by fitting video ratio inside circle with radius 115px. I picked this radius so that popover showing 16:9 video stays same size as it is now.

Improve popover size for different video ratios

---

src/meson.build

This is necessary because videos uses Gee directly, and granite built with
meson is more conservative with the linker flags it includes.
See:
- src/DiskManager.vala#L35
- src/Services/LibraryManager.vala#L38
- etc.

meson: add missing 'gee-0.8' dependency

---

src/Application.vala
src/Services/Inhibitor.vala

This PR removes the previous method of inhibiting using `simulate_activity`. Simulating user activity is bad because it keeps apps like Slack or others from displaying that "User is Idle" message, and  
To fully inhibit the session, two things need to happen:
- Using `screensaver_iface.Inhibit ("io.elementary.videos", "Playing movie");`, the screen saver gets inhibited and the screen won't turn to black after the timeout
- And using `Gtk.application.inhibit (application.get_active_window (), Gtk.ApplicationInhibitFlags.SUSPEND, "Playing Movie");` will make it so the automatic suspend never happens
- Inhibits properly when playing a video
- Computer can suspend when video is paused or app quits while playing 
- I tried to get rid of the dbus interface and use the IDLE flag mentioned in …

Use new methods of screen inhibiting

---

src/Widgets/Player/PlayerPage.vala
src/Window.vala

Fixes https://github.com/elementary/videos/issues/130
Before: Once cursor disappears on headerbar it is not shown again over headerbar until you enter play area once.
After: Cursor reappears on mouse move.

Fix disappearing cursor on headerbar

---

src/Widgets/Player/Playlist.vala
src/Widgets/Player/PlaylistItem.vala

* Use a property for `is_playing`
* bind play icon revealer to `is_playing` property
* Reduce variable scope
* Organize
* Use `add` instead of attach since we're only packing two widgets here
* Move `show_all` to the `construct` block
* Remove `row_spacing` since we never pack things vertically

PlaylistItem cleanup and revealer

---

src/Widgets/Player/PlaylistItem.vala

Show title in tooltip for playlist item

---

src/Widgets/Player/TimeWidget.vala

This PR fixes #171 by setting the slider value manually given the click event rather than relying on the Slider class to properly change the value.
Current behavior: https://imgur.com/RbeIs67
New behavior: https://imgur.com/3GWXq8I

Handle time jumping even if the user clicks above/below the slider

---

src/Application.vala

Sometimes users change their home directories, when this
happens `library-folder` will now be a non-existant path.
We can set library-folder to its new value if the path
doesn't exist.

Application: handle if library-folder doesn't exist

---

src/Widgets/Player/SettingsPopover.vala

Doesn't make sense to localize `%s`

SettingsPopover: Remove unnecessary print

---

src/Widgets/Player/Playlist.vala
src/Window.vala

See #219 for issue description
Notes:
There might be a better solution to this problem (adding an extra signal when a video starts playing and navigating the application to the player page when it is emitted), but I didn't want (and had the time) to refactor the application, so I implemented a much simpler solution. It prevents `Playlist.clear_items()` from emitting `stop_video()` (taking the application back to the welcome page) in the specific case that is described in the issue - all other use-cases remain unchanged. I hope this is acceptable.

Keep the application on the player page when a new video is opened while another on is playing

---

data/io.elementary.videos.appdata.xml.in

This is needed for appstream-generator to find the associated desktop file.
See also:
- https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-launchable
- https://github.com/ximion/appstream-generator/issues/88

Add launchable tag to appdata

---

data/io.elementary.videos.appdata.xml.in
io.elementary.videos.yml
src/Utils.vala
src/Window.vala

we need to have write access to move files to trash.
fixes #282.

Flatpak: Allow Write Access to Library and Thumbnails Cache Folders

---

data/io.elementary.videos.appdata.xml.in
io.elementary.videos.yml

Allows videos to use the codecs provided by the extension when installed.
Should fix #281.

Flatpak: Add `org.freedesktop.Platform.ffmpeg-full` Extension Point

---

io.elementary.videos.yml

May fix #291
We're shipping GL 21.08 and I think this expects 20.08 https://github.com/elementary/os/blob/master/etc/config/hooks/live/001-install-flatpaks.chroot

Flatpak: update runtime to 6.1

---

debian/control

Re-add build-deps. Even though we don't actually need these to build the package, it makes `apt build-dep` work and fixes the gettext action

Control: revert changes to build-deps

---

src/Utils.vala

We're using Gtk.Application.Inhibit, so this is unused

Utils: Remove unused session manager interface

---

src/Widgets/Player/BottomBar.vala

I can't see any difference without this code. Not sure what it's supposed to do that hexpand would already do? The earliest available commit for this mentions porting to Gtk 3.12, so I'm guessing this is just leftovers?

BottomBar: Remove get_preferred_width

---

src/Widgets/Player/PlaylistItem.vala

- Change a grid to a box and style it with Gtk.CSS instead of manually adding margins
- Remove extra `show_all`
- Prepares for Gtk4 port

PlaylistItem: Grid → Box, and .menuitem

---

src/Widgets/Player/SeekBar.vala

* Use position when setting time from playback for accuracy
* Don't set scale value when it's the source of truth
* Keep things private that aren't used outside this class
* Remove redundant value sets
* Assume the progress value we get from gstreamer is valid

SeekBar: rewrite how progress and duration are set

---

src/Application.vala
src/Widgets/Player/BottomBar.vala
src/Widgets/Player/PlayerPage.vala
src/Widgets/Player/PlaylistPopover.vala

Store repeat state in a GLib.Action so that classes aren't reaching across each other and we're not relying on UI elements to store state

Application: store repeat state in an Action

---

data/io.elementary.videos.gschema.xml
src/Services/PlaybackManager.vala
src/Widgets/Library/LibraryPage.vala
src/Widgets/Player/PlayerPage.vala
src/Widgets/Player/SeekBar.vala
src/Widgets/Player/SettingsPopover.vala
src/Widgets/WelcomePage.vala
src/Window.vala

- Use the gst provided GTK widget for playback on the PlayerPage and the playbin for the backend and as pipeline
- Preparation for #334 
- Continuation of #261 
Should be working needs some testing though. 
It sometimes crashes when resuming a video. I tracked the issue down to PreviewPopover and can confirm it is happening in master too. If you want to test without this crash comment [this line](https://github.com/elementary/videos/blob/6cfb084829970ea7f8574492fcc028c5e2991079/src/Widgets/Player/SeekBar.vala#L70C23-L70C23) (and ignore the warnings).

Use playbin with the gst gtk widget for playback

---

src/Application.vala
src/Widgets/Library/EpisodesPage.vala
src/Widgets/Library/LibraryPage.vala
src/Widgets/Player/PlayerPage.vala
src/Window.vala

- Moves the headerbar into the separate deck pages (PlayerPage, WelcomePage, LibraryPage, EpisodesPage) and makes it flat. This allows for smoother transitions between pages and keeps Videos more inline with the general OS look
- Use `Hdy.ApplicationWindow` for rounded corners
- Do some gtk4 prep while we're here
- The rounded corners are a bit buggy on the player, #335 might fix that though
Fixes #283 
Fixes #232
Screenshots:

Separate headerbars with deck pages

---

src/Widgets/Library/EpisodesPage.vala

- Use a `ListStore` with `bind_model` as `get_children` isn't available in GTK4
- No idea why but although documentation and a runtime warning say the ListBox filter_func won't work with a model, it actually does. Still with gtk4 we can/should wrap the ListStore in a FilterModel.

EpisodesPage: Preparations for GTK4

---

README.md

Since we're shipping this app as flatpak, change the build instructions to recommend `flatpak-builder` instead of meson

README: build with Flatpak

---

src/Widgets/Player/BottomBar.vala
src/Widgets/Player/PlayerPage.vala

- Derive `BottomBar` from `Gtk.EventBox` (to be replaced with controllers and a normal box in gtk4) as `Gtk.Revealer` is final in GTK4
- Do the revealing in `PlayerPage` and update some eventhandlers there

BottomBar and PlayerPage: GTK4 preparations

---

src/Services/PlaybackManager.vala

Always query position when seek finished or playing state changed to avoid delayed updating of the position label on the `SeekBar`.

PlaybackManager: Improve position querying

---

data/Application.css
data/meson.build
data/videos.gresource.xml
meson.build
src/Application.vala
src/Widgets/Player/PreviewPopover.vala
src/meson.build

Removes the borders and arrow and adds some css to make the preview popover super minimal and clean.
Got rid of the h clamp and the fancy aspect ratio stuff here since we shouldn't assume videos are 16:9 aspect ratio. If we just clamp vertically this works out well for ultrawide aspect ratios for example:

PreviewPopover: cleaner visual

---

src/Widgets/Player/PlayerPage.vala
src/Window.vala

Closes #14 
Remove all the automatic fullscreen stuff and put the regular headerbar in the revealer on the playerpage. Fixes issues with not always having access to navigation or window controls. It's still possible to fullscreen manually with a keyboard shortcut

Remove automatic fullscreen

---

.github/workflows/ci.yml
.github/workflows/merge.yml
.github/workflows/release.yml
io.elementary.videos.yml

The build is failing due to not having new enough Rust:
https://github.com/elementary/videos/actions/runs/8862630295/job/24335796428
Also add the extension to the Gettext job while we're here, so that the meson build can succeed.

Bump elementary runtime and Rust SDK extension

---

io.elementary.videos.yml

Fixes #390
Make sure to install gst-plugins-rs to `/app/lib` where GStreamer searches for by default (set in `GST_PLUGIN_SYSTEM_PATH` environment variable).

flatpak: Install gst-plugins-rs to /app/lib

---

io.elementary.videos.yml

Pin to an earlier version that works with the version of the Rust compiler that's available in the SDK

fix: pin cargo-c version

---

io.elementary.videos.yml

Fixes the following warning when building with flatpak-builder:
```
warning: redirecting to https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs.git/
Fetching git repo https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs, ref refs/heads/0.12
warning: redirecting to https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs.git/
```

Flatpak: Fix warning about redirect
