elementary/videos

- src/Widgets/Player/BottomBar.vala
Changes done:
- Remove `notify` signals in favor of properties
- Make one-line lambda functions into proper code blocks
- merged the two `play_button.clicked.connect` connections
- curly braces on one line if's
- build the revealer on the construct
> BottomBar.vala: Code cleanups

- src/Audience.vala
> GLib.Application.set_default is useless when there is only one instance

- src/Widgets/Library/EpisodesPage.vala
- src/Widgets/Library/LibraryItem.vala
- src/Window.vala
* `margin_left` and `margin_right` are replaced by start and end
* `set_default_geometry` is replaced by `set_default_size`
> Misc deprecation fixes

- src/Window.vala
Fixes a visual bug with the search entry vertical alignment/spacing
> Fix search entry valign

- data/meson.build
This is already covered by Houston CI
> Remove redundant metadata tests

- src/Audience.vala
This is covered by the `extra.pot` already
> Audience.vala: Remove extra constants

- src/Widgets/Player/PlayerPage.vala
- src/Window.vala
Revealing of bottom bar can be moved inside seek_jump_seconds() since is always called after the method.
> Cleanup code for seeking video with arrow keys

- src/Window.vala
> Window: Use FileChooserNative

- src/Widgets/Player/Playlist.vala
Fixes https://github.com/elementary/videos/issues/86
> Make playlist focusable and browsable with keyboard

- src/Widgets/Library/EpisodesPage.vala
- src/Widgets/Library/LibraryPage.vala
- src/Widgets/WelcomePage.vala
- src/Window.vala
Add video to playlist and save in current-video gsettings if played from resume button or library.
Unblocks https://github.com/elementary/videos/pull/146
> Add video to playlist if played from resume button or library

- po/POTFILES
- src/Widgets/Player/PlayerPage.vala
- src/Widgets/UnsupportedFileDialog.vala
- src/meson.build
Fixes https://github.com/elementary/videos/issues/123
> Throw error dialog in case of unsupported file

- src/Window.vala
- Wrap single line if/else in `{ }`
- use `clear_playlist ()` function
- Remove `this`
- Alphabetize private vars
- Fix indentation and spacing
> Cleanup: Window.vala

- src/Widgets/Player/PlayerPage.vala
- Make `GtkClutter.Embed` private
- Alphabetize private vars
- Remove `this`
- Wrap single line if/else in `{ }`
> Cleanup: PlayerPage.vala

- data/io.elementary.videos.appdata.xml.in
- meson.build
https://github.com/elementary/videos/compare/2.6.3...master
Where required, I've:
> Release 2.7.0

- src/Application.vala
This restores all the Library View functions inside Videos that seemingly never could be reached.
|Welcome Screen|Library View|
|:---:|:---:|
|![Screenshot from 2020-07-21 01 18 45](https://user-images.githubusercontent.com/4886639/88012584-ae182080-caf0-11ea-9359-03f9f452a8fb.png)|![Screenshot from 2020-07-21 01 19 54](https://user-images.githubusercontent.com/4886639/88012587-b07a7a80-caf0-11ea-8c9a-486647cafa12.png)|
Fixes #205
> Restore Library View functionality

- debian/rules
> Do not use destdir

- .github/workflows/main.yml
- io.elementary.videos.yml
Same as music, no gst-plugins-ugly and no org.freedesktop.ffmpeg-full extension, so codecs incompatibilities can occur.
> Add flatpak

- debian/control
- debian/io.elementary.videos.install
- debian/postinst
- debian/prerm
Same as https://github.com/elementary/screenshot/pull/222
> Install from Flatpak

- data/io.elementary.videos.appdata.xml.in
- meson.build
Should merge https://github.com/elementary/videos/pull/277 first
> Release 2.8.0

- .github/workflows/release.yml
Might want to actually have a flatpak version of videos in the stable branch on the remote before we push out the deb package that tries to install it.
> Deploy flatpak on release

- data/io.elementary.videos.appdata.xml.in
Abusing a commit to bump the release action for flatpak deployment
> Appdata: bump copyright

- data/io.elementary.videos.appdata.xml.in
- meson.build
> Release 2.8.3

- .github/workflows/ci.yml
- .github/workflows/merge.yml
- .github/workflows/release.yml
- io.elementary.videos.yml
Clutter manifest stuff copied from FlatHub's shared modules: https://github.com/flathub/shared-modules/blob/master/clutter/clutter.json
> Flatpak: bump to Platform 7

- data/io.elementary.videos.appdata.xml.in
- meson.build
Just bumps the Flatpak runtime basically
> Release 2.8.4

- src/Widgets/Library/LibraryItem.vala
- Update margins, expand, etc.
- Use stack for switching between spinner and poster
- `FileChooser.response` instead `run ()`
> LibraryItem: Simplifications and preparations for GTK4

- src/Services/PlaybackManager.vala
- src/Widgets/Player/SettingsPopover.vala
- Update some margins etc.
- Replace `FileChooserButton` with a normal `Button`
> SettingsPopover: Preparations for GTK4

- src/Widgets/Player/PreviewPopover.vala
- src/Widgets/Player/SeekBar.vala
- Use playbin with gst GTK widget
> PreviewPopover: Preparations for GTK4

- meson.build
> Meson: update to 3.0.0

- data/io.elementary.videos.gschema.xml
- src/Application.vala
- src/Services/PlaybackManager.vala
- src/Widgets/Player/PlaylistPopover.vala
Toggle through the modes by clicking the repeat button multiple times
> Support repeat one and repeat all

- src/Services/PlaybackManager.vala
- src/Widgets/HeaderBar.vala
- src/Widgets/Library/EpisodesPage.vala
- src/Widgets/Library/LibraryPage.vala
- src/Widgets/Player/PlayerPage.vala
- src/Widgets/WelcomePage.vala
- src/Window.vala
Replaces Adw.Leaflet with Adw.NavigationView
* Fixes some janky title stuff. Make sure titles always correctly reflect the view we're on
* Move welcome page headerbar into the welcome page
* Remove accels that are already handled by the navigation page
> Leaflet → NavigationView

- data/videos.metainfo.xml.in
- meson.build
Small hotfix release to get #391 out.
First release I'm doing so if I'm doing something wrong lmk :)
> Release 8.0.1

- src/Widgets/Library/LibraryItem.vala
- src/Widgets/Player/SettingsPopover.vala
- src/Window.vala
- src/meson.build
- Use Gtk.FileDialog to open video files
- Use Gtk.FileDialog to choose cover image
- Use Gtk.FileDialog to choose subtitle
> Use Gtk.FileDialog
